name: liso
description: Liso
publish_to: "none"
version: 0.4.1+20

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # STATE MANAGEMENT
  get: ^4.6.5

  # CRYTPOGRAPHY + SECURITY
  secrets:
    path: ../secrets
  alchemy_web3:
    git: https://github.com/oliverbytes/alchemy_web3.git
  web3dart: ^2.3.5 # Ethereum
  eth_sig_util: ^0.0.7 # Ethereum signature
  bip39: ^1.0.6 # Mnemonic Seed Phrases
  bip32: ^2.0.0 # Derive Path
  hex: ^0.2.0 # Hex encoding & decoding
  encrypt: ^5.0.1 # File Encryption
  local_auth: ^2.0.2 # check biometric availability
  walletconnect_dart: ^0.0.10
  otp: ^3.0.4

  # FIREBASE
  firebase_core: 1.17.1
  firebase_analytics: 9.1.9
  firebase_crashlytics: 2.8.1
  firebase_performance: 0.8.0+13
  firebase_remote_config: 2.0.8
  firebase_auth: 3.3.19
  cloud_firestore: 3.1.17
  # firebase_app_check: ^0.0.6+9

  # IO
  hive: ^2.2.1 # database
  path_provider: ^2.0.10
  path: ^1.8.1
  filesize: ^2.0.1 # file size calculator
  file_picker: ^4.6.1 # exporting + importing
  http: ^0.13.4 # web3dart client
  minio: ^3.5.0 # S3 API
  coingecko_api: ^1.0.2+2 # Coingecko API

  # UI
  line_icons: ^2.0.1 # icons
  font_awesome_flutter: ^10.1.0 # icons
  iconsax: ^0.0.8
  flex_color_scheme: 5.0.1 # themes
  simple_animations: ^4.0.2
  blur: ^3.1.0 # blurring of seed phrases
  flutter_json_viewer: ^1.0.1 #json viewer
  chips_input: ^0.1.0 # tags input
  flutter_swipe_action_cell: ^3.0.2
  flutter_quill:
    git: https://github.com/oliverbytes/flutter-quill.git
  badges: ^2.0.2 # pending changes indicator
  cached_network_image: ^3.2.1 # load remote images
  percent_indicator: ^4.2.2 # circular progress indicator
  flutter_svg: ^1.0.3 # dice bear avatars
  qr_flutter: ^4.0.0 # generate QR Codes
  skeletons: ^0.0.3 # shimmer loading effects

  # TOOLS
  url_launcher: ^6.1.2
  supercharged: ^2.1.1 # useful utils
  timeago: ^3.2.2
  flutter_local_notifications: ^9.5.3+1
  either_dart: ^0.1.4 # functional programming + error handling
  intl: ^0.17.0 # date formatting
  share_plus: ^4.0.5 # exporting files and sharing texts
  equatable: ^2.0.3
  app_settings: ^4.1.6
  uuid: ^3.0.6 # unique identifiers for items
  window_manager: ^0.2.3 # set desktop window size
  flutter_displaymode: ^0.4.0 # allow higher refresh rates
  console_mixin: ^0.0.1 # logger
  random_string: ^2.3.1 # random string generator
  random_password_generator: ^0.2.1 # random password generator

  # INFO
  device_info_plus: ^3.2.3
  package_info_plus: ^1.4.2
  connectivity_plus: ^2.3.2 # internet connectivity checking

dev_dependencies:
  # flutter_test:
  #   sdk: flutter

  flutter_lints: ^2.0.1
  hive_generator: ^1.1.3 # hive database
  build_runner: ^2.1.11
  flutter_native_splash: ^2.2.0+1
  dart_code_metrics: ^4.15.2 # checking unused stuffs

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: RobotoFlex
      fonts:
        - asset: fonts/RobotoFlex.ttf
