name: liso
description: Liso - Encrypted Seed Vault
publish_to: "none"
version: 0.3.0+11

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # STATE MANAGEMENT
  get: 4.6.1

  # CRYTPO
  web3dart: ^2.3.3
  bip39: ^1.0.6
  hex: ^0.2.0
  cryptography: ^2.0.5

  # FIREBASE
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.6
  firebase_analytics: ^9.1.0
  firebase_crashlytics: ^2.5.1
  firebase_performance: ^0.8.0+5

  # GOOGLE
  google_sign_in: ^5.2.3
  googleapis: ^7.0.0
  

  # IO
  hive: 2.0.5
  hive_flutter: 1.1.0
  get_storage: 2.0.3 # persistence
  path_provider: 2.0.8
  path: ^1.8.1
  file_picker: ^4.3.3 # exporting + importing

  # UI
  line_icons: ^2.0.1
  flex_color_scheme: 4.2.0 # themes
  desktop_window: ^0.4.0 # set desktop window size
  flutter_svg: 1.0.3
  simple_animations: 4.0.1
  bubble_tab_indicator: 0.1.6
  blur: ^3.0.0
  flutter_json_viewer: ^1.0.1 #json viewer

  # TOOLS
  logger: ^1.1.0
  url_launcher: 6.0.18
  supercharged: 2.1.1
  flutter_linkify: 5.0.2
  timeago: 3.2.2
  permission_handler: 8.3.0
  flutter_local_notifications: ^9.2.0
  either_option: 2.0.1-dev.1

  # INFO
  device_info_plus: 3.2.1
  package_info_plus: ^1.3.0

dev_dependencies:
  # flutter_test:
  #   sdk: flutter

  flutter_lints: ^1.0.0
  hive_generator: 1.1.2
  build_runner: ^2.1.7
  flutter_native_splash: ^2.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/origins/
