name: liso
description: Liso
publish_to: "none"
version: 1.3.2+64

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # CORE FRAMEWORK
  app_core:
    path: ../../Stackwares/app-core

  # Server Core Client
  core_client:
    path: ../../core-serverpod/core_client

  # CRYTPOGRAPHY + SECURITY
  secrets:
    path: ../secrets
  # alchemy_web3:
  #   git:
  #     url: https://github.com/oliverbytes/alchemy_web3.git
  #     ref: 3adc07eba84dd1a4ab58dc09ea6baa803576dee7
  web3dart: ^3.0.1 # Ethereum
  eth_sig_util: ^0.0.9 # Ethereum signature
  bip39: ^1.0.6 # Mnemonic Seed Phrases
  bip32: ^2.0.0 # Derive Path
  hex: ^0.2.0 # Hex encoding & decoding
  encrypt: 5.0.1 # important to keep at 5.0.1 to avoid "Invalid or corrupted pad block"
  otp: ^3.2.0

  # IO
  filesize: ^2.0.1 # file size calculator
  file_picker: ^8.1.2 # exporting + imØporting vault file
  share_plus: ^12.0.0

  # # API
  # coingecko_api: ^2.0.2
  
  # UI
  blur: ^4.0.2 # blurring of seed phrases
  flutter_json_viewer: ^1.0.1 #json viewer
  flutter_swipe_action_cell: ^3.1.6
  flutter_quill: ^11.4.2
  badges: ^3.1.2 # pending changes indicator
  qr_flutter: ^4.1.0 # generate QR Codes
  icons_plus: ^5.0.0
  dash_flags: ^0.1.1 # replace with icons_plus dash flags

  # TOOLS
  equatable: ^2.0.7
  random_string_generator: ^2.0.0
  worker_manager: ^7.2.6 # multi threading
  csv: ^6.0.0 # csv parsing tool

dependency_overrides:
  pointycastle: ^4.0.0
  either_dart: ^1.0.0
  web: ^1.1.1 # make file_picker work

dev_dependencies:
  flutter_lints: ^6.0.0
  icons_launcher: ^3.0.3
  flutter_native_splash: ^2.4.6
  build_runner: ^2.8.0
  # dependency_validator: ^4.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/