name: liso
description: Liso
publish_to: "none"
version: 1.1.2+49

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

    # CORE FRAMEWORK
  app_core:
    path: ../../Stackwares/app-core

  # CRYTPOGRAPHY + SECURITY
  secrets:
    path: ../secrets
  # alchemy_web3:
  # git: https://github.com/oliverbytes/alchemy_web3.git
  alchemy_web3:
    git:
      url: https://github.com/oliverbytes/alchemy_web3.git
      ref: 3adc07eba84dd1a4ab58dc09ea6baa803576dee7
  web3dart: ^2.6.1 # Ethereum
  eth_sig_util: ^0.0.9 # Ethereum signature
  bip39: ^1.0.6 # Mnemonic Seed Phrases
  bip32: ^2.0.0 # Derive Path
  hex: ^0.2.0 # Hex encoding & decoding
  encrypt: ^5.0.1
  otp: ^3.1.4

  # IO
  filesize: ^2.0.1 # file size calculator
  file_picker: ^5.3.2 # exporting + importing vault file
  share_plus: ^7.0.1

  # API
  # minio: ^3.5.0 # S3 API
  # minio:
  #   git:
  #     url: https://github.com/oliverbytes/minio-dart.git
  #     ref: 076c9f33729713c06f885448d86e79092c09d11c
    # git: https://github.com/oliverbytes/minio-dart.git
  # coingecko_api: ^1.1.1+1 # Coingecko API
  coingecko_api:
    git:
      url: https://github.com/oliverbytes/coingecko_api.git
      ref: 6f3b63c2a89d2160c60a4b84bd348f69e719b3ff

  supabase_auth_ui: ^0.2.0

  # UI
  iconsax: ^0.0.8
  font_awesome_flutter: ^10.4.0 # icons
  blur: ^3.1.0 # blurring of seed phrases
  flutter_json_viewer: ^1.0.1 #json viewer
  flutter_swipe_action_cell: ^3.1.0
  flutter_quill: ^8.1.10
  badges: ^3.1.1 # pending changes indicator
  qr_flutter: ^4.1.0 # generate QR Codes
  skeletons: ^0.0.3 # shimmer loading effects

  # TOOLS
  equatable: ^2.0.5
  random_string_generator: ^2.0.0
  worker_manager: ^4.4.6 # multi threading
  flutter_autofill_service: ^0.14.0 # android autofill plugun
  csv: ^5.0.2 # csv parsing tool

dependency_overrides:
  # intl: ^0.17.0
  # extended_image: ^8.0.1
  win32: 5.0.2
  either_dart: ^1.0.0

dev_dependencies:
  dependency_validator: ^3.2.2
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - google_fonts/
