name: liso
description: Liso
publish_to: "none"
version: 1.2.5+57

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # CORE FRAMEWORK
  app_core:
    path: ../../Stackwares/app-core

  # CRYTPOGRAPHY + SECURITY
  secrets:
    path: ../secrets
  alchemy_web3:
    git:
      url: https://github.com/oliverbytes/alchemy_web3.git
      ref: 3adc07eba84dd1a4ab58dc09ea6baa803576dee7
  web3dart: ^2.6.1 # Ethereum
  eth_sig_util: ^0.0.9 # Ethereum signature
  bip39: ^1.0.6 # Mnemonic Seed Phrases
  bip32: ^2.0.0 # Derive Path
  hex: ^0.2.0 # Hex encoding & decoding
  encrypt: 5.0.1
  otp: ^3.1.4

  # IO
  filesize: ^2.0.1 # file size calculator
  file_picker: ^8.1.2 # exporting + importing vault file
  share_plus: ^10.0.2

  # API
  coingecko_api:
    git:
      url: https://github.com/oliverbytes/coingecko_api.git
      ref: 5f9cf89c215e0a8e9710f9ffcf24074666df8e78

  # UI
  blur: ^4.0.0 # blurring of seed phrases
  flutter_json_viewer: ^1.0.1 #json viewer
  flutter_swipe_action_cell: ^3.1.4
  # flutter_quill: ^9.3.11
  flutter_quill:
    git:
      url: https://github.com/monoforest/flutter-quill.git
      ref: 62b19ee2bf510b566c1330a7f177d3dfe1142a32
  badges: ^3.1.2 # pending changes indicator
  qr_flutter: ^4.1.0 # generate QR Codes
  icons_plus: ^5.0.0

  # TOOLS
  equatable: ^2.0.5
  random_string_generator: ^2.0.0
  worker_manager: ^4.4.6 # multi threading
  csv: ^6.0.0 # csv parsing tool
  # flutter_autofill_service: ^0.14.0 # android autofill plugun
  flutter_autofill_service: 
    git:
      url: https://github.com/kee-org/flutter_autofill_service.git

dependency_overrides:
  either_dart: ^1.0.0
  web: ^1.0.0 # make file_picker work
  # fix pointer_interceptor error https://github.com/FlutterFlow/flutterflow-issues/issues/3601
  pointer_interceptor: ^0.10.1+1 

dev_dependencies:
  flutter_lints: ^4.0.0
  icons_launcher: ^2.1.7
  flutter_native_splash: ^2.4.1
  build_runner: ^2.4.12
  dependency_validator: ^4.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/