name: liso
description: Liso
publish_to: "none"
version: 1.1.0+47

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

    # CORE FRAMEWORK
  app_core:
    path: ../../Stackwares/app-core

  # CRYTPOGRAPHY + SECURITY
  secrets:
    path: ../secrets
  # alchemy_web3:
  # git: https://github.com/oliverbytes/alchemy_web3.git
  alchemy_web3:
    git:
      url: https://github.com/oliverbytes/alchemy_web3.git
      ref: 3adc07eba84dd1a4ab58dc09ea6baa803576dee7
  web3dart: ^2.3.5 # Ethereum
  eth_sig_util: ^0.0.9 # Ethereum signature
  bip39: ^1.0.6 # Mnemonic Seed Phrases
  bip32: ^2.0.0 # Derive Path
  hex: ^0.2.0 # Hex encoding & decoding
  encrypt: ^5.0.1 # File Encryption
  otp: ^3.1.3

  # IO
  filesize: ^2.0.1 # file size calculator
  file_picker: ^5.2.3 # exporting + importing vault file
  share_plus: ^6.3.0

  # API
  # minio: ^3.5.0 # S3 API
  minio:
    git: https://github.com/oliverbytes/minio-dart.git
  coingecko_api: ^1.1.0+2 # Coingecko API
  supabase_auth_ui: ^0.1.0+2

  # UI
  iconsax: ^0.0.8
  font_awesome_flutter: ^10.2.1 # icons
  blur: ^3.1.0 # blurring of seed phrases
  flutter_json_viewer: ^1.0.1 #json viewer
  flutter_swipe_action_cell: ^3.0.4
  flutter_quill: ^7.2.0
  badges: ^2.0.3 # pending changes indicator
  percent_indicator: ^4.2.2 # circular progress indicator
  flutter_svg: ^1.1.6 # dice bear avatars
  qr_flutter: ^4.0.0 # generate QR Codes
  skeletons: ^0.0.3 # shimmer loading effects

  # TOOLS
  equatable: ^2.0.5
  random_string_generator: ^2.0.0
  humanizer: ^2.0.0
  worker_manager: ^4.4.6 # multi threading
  flutter_autofill_service: ^0.14.0 # android autofill plugun
  csv: ^5.0.2 # csv parsing tool

dependency_overrides:
  package_info_plus: ^3.0.2
  firebase_core: ^2.3.0
  cloud_functions: ^4.0.4
  device_info_plus: ^8.0.0
  intl: ^0.17.0
  extended_image: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - google_fonts/
