name: liso
description: Liso - Encrypted Seed Vault
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # STATE MANAGEMENT
  get: ^4.6.1

  # CRYTPOGRAPHY + SECURITY
  web3dart: ^2.3.5
  bip39: ^1.0.6
  hex: ^0.2.0
  cryptography: ^2.0.5
  biometric_storage: ^4.1.0 # secure storage with biometrics
  local_auth: ^1.1.11 # check biometric availability

  # FIREBASE
  firebase_core: 1.13.1
  firebase_auth: 3.3.11
  firebase_analytics: 9.1.2
  firebase_crashlytics: 2.5.3
  firebase_performance: 0.8.0+7
  firebase_remote_config: ^2.0.4
  # firebase_app_check: ^0.0.6+9

  # GOOGLE
  google_sign_in: ^5.2.4
  googleapis: ^8.1.0

  # WORKAROUND
  desktop_webview_auth: ^0.0.6 # MacOS Google Sign In
  flutter_displaymode: ^0.4.0 # allow higher refresh rates

  # IO
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  get_storage: ^2.0.3 # persistence
  path_provider: ^2.0.9
  path: ^1.8.1
  filesize: ^2.0.1
  file_picker: ^4.5.1 # exporting + importing
  archive: ^3.3.0 # archiving hive boxes
  minio: ^3.5.0 # Filebase API
  ipfs_rpc: # ^0.0.1 # decentralized storage server
    path: ../../packages/ipfs_rpc/

  # UI
  line_icons: ^2.0.1
  font_awesome_flutter: ^10.1.0
  flex_color_scheme: ^4.2.0 # themes
  desktop_window: ^0.4.0 # set desktop window size
  flutter_svg: ^1.0.3
  simple_animations: ^4.0.1
  bubble_tab_indicator: ^0.1.6
  blur: ^3.1.0 # blurring of seed phrases
  flutter_json_viewer: ^1.0.1 #json viewer
  chips_input: ^0.1.0 # tags input
  flutter_swipe_action_cell: ^2.2.0
  flutter_quill: ^4.1.1 # rich text editor

  # TOOLS
  logger: ^1.1.0
  url_launcher: ^6.0.20
  supercharged: ^2.1.1
  flutter_linkify: ^5.0.2
  timeago: ^3.2.2
  permission_handler: ^9.2.0
  flutter_local_notifications: ^9.4.0
  either_option: 2.0.1-dev.1
  intl: ^0.17.0
  share_plus: ^4.0.3
  equatable: ^2.0.3

  # INFO
  device_info_plus: ^3.2.2
  package_info_plus: ^1.4.0

dev_dependencies:
  # flutter_test:
  #   sdk: flutter

  flutter_lints: ^1.0.4
  hive_generator: ^1.1.2
  build_runner: ^2.1.8
  flutter_native_splash: ^2.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/origins/
