# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Builds the iOS app for release (IPA file)"
  lane :deploy do |options|
    UI.message("Building Flutter iOS release...")
    sh "flutter build ios --release"

    UI.message("Building iOS IPA file...")
    build_ios_app(
      scheme: "Runner",
      configuration: "Release",
      silent: true,
      clean: true,
      output_directory: "build/fastlane/ipa",
      output_name: "Runner.ipa",
      export_method: "app-store" # لو بتبني لـ TestFlight أو App Store
    )

    UI.success("iOS IPA built successfully and located at: build/fastlane/ipa/Runner.ipa 🎉")
  end
end
